micronaut:
  application:
    name: loginService
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  caches:
    my-cache:
      maximumSize: 20
datasources:
  default:
    driver-class-name: oracle.jdbc.OracleDriver
    db-type: oracle
    dialect: ORACLE
elasticsearch.httpHosts: http://localhost:9200,http://127.0.0.2:9200
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
